# Generated by Django 5.2.5 on 2025-08-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('architectural', 'معماري (Architectural)'), ('structural', 'إنشائي (Structural)'), ('electrical', 'كهرباء (Electrical)'), ('mechanical', 'ميكانيكا (Mechanical)'), ('exterior', 'تصميم خارجي (Exterior Design)')], default='architectural', max_length=20),
        ),
    ]
